#!/usr/bin/python -u
# Note that running python with the `-u` flag is required on Windows,
# in order to ensure that stdin and stdout are opened in binary, rather
# than text, mode.

import sys, json, struct
import subprocess

# Read a message from stdin and decode it.
def getMessage():
  rawLength = sys.stdin.read(4)
  if len(rawLength) == 0:
      sys.exit(0)
  messageLength = struct.unpack('@I', rawLength)[0]
  message = sys.stdin.read(messageLength)
  return json.loads(message)

# Encode a message for transmission, given its content.
def encodeMessage(messageContent):
  encodedContent = json.dumps(messageContent)
  encodedLength = struct.pack('@I', len(encodedContent))
  return {'length': encodedLength, 'content': encodedContent}

# Send an encoded message to stdout.
def sendMessage(encodedMessage):
  sys.stdout.write(encodedMessage['length'])
  sys.stdout.write(encodedMessage['content'])
  sys.stdout.flush()

def handleSwitchTab(receivedMessage):
    """
    Unpack message and use the list as input to dmenu. Get back the result and send it back to the
    browser.
    """
    tablist = "\n".join(receivedMessage.split('\n')[1:])
    proc = subprocess.Popen(['dmenu', '-l', '10', '-p', 'Switch:'], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    # proc.stdin.write(tablist)
    sel = proc.communicate(input=tablist)[0]

    sendMessage(encodeMessage("switch-tab {0}".format(sel.split('|')[0])))

while True:
  receivedMessage = getMessage()
  if (receivedMessage == "ping"):
    sendMessage(encodeMessage("pong"))
  elif receivedMessage.startswith("switch-tab"):
    handleSwitchTab(receivedMessage)
